#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X
bspc monitor eDP1  -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         7
bspc config top_padding          25
bspc config window_gap           30
bspc config split_ratio          0.50

bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config normal_border_color   "#8000FF"
bspc config active_border_color   "#8000FF"
bspc config focused_border_color  "#FF80FF"
bspc config presel_feedback_color "#FF0000"

bspc config pointer_follows_focus      true
#bspc config remove_disabled_monitors   true
#bspc config remove_unplugged_monitors  true
#bspc config merge_overlapping_monitors true

bspc rule -a \* rectangle 950x950+0+0 center=true
bspc rule -a Emacs state=tiled follow=on

# Autostart
feh --bg-fill ~/Pictures/walls/purpleSpirals.png
xfce4-power-manager
~/.config/polybar/launch.sh
emacs --daemon &
compfy --config ~/.config/compfy/compfy.conf &
