#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config border_width         5
# bspc config top_padding          25
bspc config top_padding          5
bspc config window_gap           30
bspc config split_ratio          0.50

bspc config borderless_monocle   false
bspc config gapless_monocle      false

# Purple and pink color scheme
bspc config normal_border_color   "#8000FF"
bspc config active_border_color   "#8000FF"
bspc config focused_border_color  "#FF80FF"
bspc config presel_feedback_color "#FF0000"

bspc config pointer_follows_focus      true
bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true
bspc config merge_overlapping_monitors true

bspc rule -a \* rectangle 950x950+0+0 center=true
bspc rule -a Emacs state=tiled follow=on

# Autostart
xrandr --output HDMI-1 --mode 1920x1080 --primary --output eDP-1 --mode 1920x1080
xrandr --output eDP-1 --off
polybar &
emacs --daemon &
