#!/usr/bin/env bash
# This is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#FEFFD1'

# remove all existing keybindings
hc keyunbind --all

# Keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

# Basic functions
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q chain , close , remove
hc keybind $Mod-space spawn kitty

# Focusing clients
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right

# Moving clients
hc keybind $Mod-Shift-h chain , shift left  , focus up , shift right , focus left
hc keybind $Mod-Shift-j chain , shift down  , focus up , shift up    , focus down
hc keybind $Mod-Shift-k chain , shift up    , focus up , shift down  , shift down  , focus up
hc keybind $Mod-Shift-l chain , shift right , focus up , shift left  , focus right

# Splitting frames
hc keybind $Mod-Mod1-h  chain , split  left   0.5 , focus left
hc keybind $Mod-Mod1-j  chain , split  bottom 0.5 , focus down
hc keybind $Mod-Mod1-k  chain , split  top    0.5 , focus up
hc keybind $Mod-Mod1-l  chain , split  right  0.5 , focus right

# Resizing frames
resizestep=0.02
hc keybind $Mod-Control-h resize left  #+$resizestep
hc keybind $Mod-Control-j resize down  #+$resizestep
hc keybind $Mod-Control-k resize up    #+$resizestep
hc keybind $Mod-Control-l resize right #+$resizestep

# Let the current frame explode into subframes
# hc keybind $Mod-Shift-space split explode

# Tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# Layouting
hc keybind $Mod-r remove
#hc keybind $Mod-Shift-f fullscreen toggle
hc keybind $Mod-f floating toggle
#hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
#hc keybind $Mod-Shift-d set_attr clients.focus.decorated toggle
#hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
#hc keybind $Mod-Control-m jumpto last-minimized
# hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
#hc keybind $Mod-space                                                           \
#            or , and . compare tags.focus.curframe_wcount = 2                   \
#                     . cycle_layout +1 vertical horizontal max vertical grid    \
#               , cycle_layout +1

# Mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# Focus
# hc keybind $Mod-BackSpace   cycle_monitor
# hc keybind $Mod-Tab         cycle_all +1
# hc keybind $Mod-Shift-Tab   cycle_all -1
# hc keybind $Mod-c cycle
# hc keybind $Mod-i jumpto urgent

# Theme
hc attr theme.tiling.reset        1
hc attr theme.floating.reset      1
hc attr theme.normal.color        '#8000FF'
hc set  frame_border_normal_color '#8000FF'
hc set  frame_border              '#8000FF'
hc set  frame_bg_normal_color     '#8000FF'
hc set  frame_border_active_color '#FF80FF'
hc set  frame_bg_active_color     '#FF80FF'
hc set  frame_border_width        7
hc set  show_frame_decorations    'focused_if_multiple'
hc set  frame_bg_transparent      on
hc set  frame_transparent_width   2
hc set  frame_gap                 35

hc attr theme.title_height           0
hc attr theme.title_when             never
hc attr theme.title_font             '3270 Nerd Font Propo-Condensed:pixelsize=12'
hc attr theme.title_depth            0  # space below the title's baseline
hc attr theme.active.color           '#8FCFAFAA'
hc attr theme.title_color            '#FFFFFF'
hc attr theme.urgent.color           '#7811A1dd'
hc attr theme.tab_color              '#1F1F1Fdd'
hc attr theme.active.tab_color       '#2B4F0Add'
hc attr theme.active.tab_outer_color '#6C8257'
hc attr theme.active.tab_title_color '#ababab'
hc attr theme.normal.title_color     '#898989'
hc attr theme.inner_width            0
hc attr theme.inner_color            black
hc attr theme.border_width           0
hc attr theme.floating.border_width  5
hc attr theme.floating.outer_width   0
hc attr theme.floating.outer_color   black
hc attr theme.active.inner_color     '#789161'
hc attr theme.urgent.inner_color     '#9A65B0'
hc attr theme.normal.inner_color     '#000000'

# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.tiling.outer_width 0
hc attr theme.background_color '#141414'

# Window gaps and padding
hc set window_gap                0
hc set frame_padding             0
hc set smart_window_surroundings off
hc set smart_frame_surroundings  off
hc set mouse_recenter_gap        0

# Rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule floatplacement=center
#hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1920x1080
# or simply:
hc detect_monitors

#######################
### CUSTOM KEYBINDS ###
#######################
hc keybind $Mod-Shift-Control-h  spawn kitty bash -c "cat ~/.config/herbstluftwm/autostart | less"
hc keybind $Mod-s                spawn kitty bash -c "df -h | less"
hc keybind XF86AudioRaiseVolume  spawn pactl set-sink-volume @DEFAULT_SINK@ +5%
hc keybind XF86AudioLowerVolume  spawn pactl set-sink-volume @DEFAULT_SINK@ -5%
hc keybind XF86AudioMute         spawn pactl set-sink-mute @DEFAULT_SINK@ toggle
hc keybind Shift-Control-f       spawn rofi -show drun
hc keybind Control-Mod1-Delete   spawn kitty btop
hc keybind Mod1-e                spawn emacsclient -c -e "(ibuffer)"
hc keybind Mod1-t                spawn emacsclient -c ~/Desktop/notes/dailyNote.org
hc keybind XF86Calculator        spawn emacsclient -c -e "(full-calc)"
hc keybind Mod1-c                spawn emacsclient -c -e "(=calendar)"
hc keybind Mod1-m                spawn emacsclient -c -e "(lunar-phases)"
hc keybind Print                 spawn xfce4-screenshooter -r

### CUSTOM AUTO-STARTUP PROGRAMS ###
feh --bg-fill ~/Pictures/walls/purpleSpirals.png
xfce4-power-manager
~/.config/polybar/launch.sh
emacs --daemon &
compfy --config ~/.config/compfy/compfy.conf &
